name: Copy Vale files from source repository and create pull request

on:
  push:
    branches:
      - main
  schedule:
    # ATTENTION: To reduce GitHub Action usage, set cron to '0 0 1 * *' (at 12:00 AM on the 1st of the month) when not inactive
    - cron: '0 0 1 * *'  # Schedule the workflow to run every XX:00, XX:15, XX:30, and XX:45 ('0,15,30,45 * * * *')

jobs:
  copy_vale_files_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the destination repository
        uses: actions/checkout@v3

      - name: Copy Vale files from sandbox-copy-docs-source-2
        uses: actions/checkout@v3
        with:
          repository: josh-wong/sandbox-copy-docs-source-2  # This repository contains the main source of Vale contents.
          path: sandbox-copy-docs-source-2  # Replace with the desired path to clone the repository
          ref: main  # Replace with the desired branch name

      - name: Check for changes
        id: check_changes
        # Set the echo output variable based on changes
        run: |
          git diff --quiet HEAD -- vale .vale.ini sandbox-copy-docs-source-2
          echo "has_changes=true" >> "$VALE_OUTPUT"
            
      - name: Move Vale files to destination
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          cp -r vale/ .vale.ini /

      - name: Configure git
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "joshuarwong@gmail.com"
          git config --local user.name "josh-wong"

      - name: Create branch
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git checkout -b add-updated-vale-style-guide
          git add .
          git commit -m "Copy Vale style guide from source repository"

      - name: Push branch
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.VALE }}
          branch: add-updated-vale-style-guide

      - name: Create pull request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.VALE }}
          branch: add-updated-vale-style-guide
          title: Copy Vale style guide from source repository
          body: |
            This PR includes updates to the Vale style guide (`.vale.ini` and the "vale" folder), which were made in the `sandbox-copy-docs-source-2` source repository.

          base: main
          draft: false
